spring:
  config:
    activate:
      on-profile: localhost
    import: optional:file:./application-local.yml
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/erpcorporativo?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.type.descriptor.sql: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

server:
  forward-headers-strategy: framework
